name: Deploy MkDocs site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'   # Use the appropriate Python version

      # Step 3: Install MkDocs and plugins
      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-simple-blog
          pip install ghp-import       # Required for deployment

      # Step 4: Build the MkDocs site
      - name: Build MkDocs site
        run: mkdocs build

    # Step 5: Copy CNAME to the build directory
      - name: Copy CNAME file
        run: |
          echo "2024.newspeak.house" > site/CNAME
        working-directory: ${{ github.workspace }}

      # Step 6: Confirm CNAME file is present
      - name: Check CNAME file
        run: cat site/CNAME

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force --remote-branch gh-pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
