name: Deploy MkDocs site

on:
  push:
    branches:
      - gh-pages   # This specifies the branch to watch for changes (replace 'main' with your default branch name)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'   # Use the appropriate Python version

      # Step 3: Install MkDocs and plugins
      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-simple-blog
          pip install ghp-import       # Required for deployment

      # Step 4: Build the MkDocs site
      - name: Build MkDocs site
        run: mkdocs build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force --remote-branch gh-pages  # Modify branch name if needed
        env:
          # GitHub token to authorize pushing to the gh-pages branch
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
