name: Deploy MkDocs site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install MkDocs and plugins
      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-simple-blog
          pip install ghp-import

      # Step 4: Build MkDocs site
      - name: Build MkDocs site
        run: mkdocs build

      # Step 5: Deploy to GitHub Pages with custom CNAME
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force --remote-branch gh-pages --cname "2024.newspeak.house"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
